package cn.edu.sustech.cs209.chatting.common;

public enum MessageType {
           CONNECT,DISCONNECT,ASKFORCHAT,SUCCESS,FAIL,NEWCLIENTJION,
    SOMEONELEAVE,SENDMESSAGE,REFRESHUSERLIST,REFRESHCHATTHINGWINDOWS,
    CREATNEWROOM,INVITEYOUTOROOM,REFRESHCHATLIST
}
